export const GET_DATA_LOADING="GET_DATA_LOADING";
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS";
export const GET_DATA_ERROR="GET_DATA_ERROR";

export const POST_DATA_LOADING="POST_DATA_LOADING";
export const POST_DATA_SUCCESS="POST_DATA_SUCCESS";
export const POST_DATA_ERROR="POST_DATA_ERROR";

export const EDIT_DATA_LOADING="EDIT_DATA_LOADING";
export const EDIT_DATA_SUCCESS="EDIT_DATA_SUCCESS";
export const EDIT_DATA_ERROR="EDIT_DATA_ERROR";

export const DELETE_DATA_LOADING="DELETE_DATA_LOADING";
export const DELETE_DATA_SUCCESS="DELETE_DATA_SUCCESS";
export const DELETE_DATA_ERROR="DELETE_DATA_ERROR";
